name: Weather App CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  # ----------------
  # BUILD
  # ----------------
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Inject API key
        run: |
          sed 's/__API_KEY__/${{ secrets.WEATHER_API_KEY }}/g' app/config.template.js > app/config.js

      - name: Build Docker Image
        run: docker build -t weather-app .

  # ----------------
  # TEST
  # ----------------
  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Inject API key
        run: |
          sed 's/__API_KEY__/${{ secrets.WEATHER_API_KEY }}/g' app/config.template.js > app/config.js

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build Docker Image
        run: docker build -t weather-app .

      - name: Run container
        run: docker run -d -p 8080:80 --name weather-test weather-app

      - name: Run tests
        run: npm test

      - name: Stop container
        run: docker stop weather-test

  # ----------------
  # DEPLOY
  # ----------------
  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Azure VM
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          envs: WEATHER_API_KEY = ${{ secrets.WEATHER_API_KEY }}

          # script: |
          #   docker stop weather-app || true
          #   docker rm weather-app || true
          #   docker rmi weather-app || true

          #   rm -rf weather-app-repo
          #   git clone https://github.com/CKMolinga/weather-app-devops.git weather-app-repo

          #   cd weather-app-repo

          #   sed "s/__API_KEY__/${WEATHER_API_KEY}/g" app/config.template.js > app/config.js

          #   docker build -t weather-app .

          #   docker run -d -p 80:80 --name weather-app weather-app

          script: |
            # Stop and remove ALL containers (including old ones)
            docker stop $(docker ps -q) || true
            docker rm $(docker ps -aq) || true 

            # Remove old image
            docker rmi weather-app || true

            # Clone latest code
            rm -rf weather-app-repo
            git clone https://github.com/CKMolinga/weather-app-devops.git weather-app-repo

            cd weather-app-repo

            # Inject API key
            sed "s/__API_KEY__/${WEATHER_API_KEY}/g" app/config.template.js > app/config.js

            # Build image
            docker build -t weather-app .

            # Run container on port 80
            docker run -d -p 80:80 --name weather-app weather-app
