name: Weather App CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  # ----------------
  # BUILD
  # ----------------
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Inject API key
        run: |
          sed 's/__API_KEY__/${{ secrets.WEATHER_API_KEY }}/g' app/config.template.js > app/config.js

      - name: Build Docker Image
        run: docker build -t weather-app .

  # ----------------
  # TEST
  # ----------------
  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Inject API key
        run: |
          sed 's/__API_KEY__/${{ secrets.WEATHER_API_KEY }}/g' app/config.template.js > app/config.js

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install --include=dev

      - name: Build Docker Image
        run: docker build -t weather-app .

      - name: Run container
        run: docker run -d -p 8080:80 --name weather-test weather-app

      - name: Run tests
        run: npm test

      - name: Stop container
        run: docker stop weather-test

  # deploy:
  #   needs: build
  #   runs-on: ubuntu-latest

  #   if: github.ref == 'refs/heads/main'

  #   steps:
  #     - name: Deploy to Azure VM
  #       uses: appleboy/ssh-action@master

  #       with:
  #         host: ${{ secrets.AZURE_HOST }}
  #         username: ${{ secrets.AZURE_USER }}
  #         key: ${{ secrets.AZURE_SSH_KEY }}

  #         script: |

  #           cd weather-app || git clone https://github.com/YOUR_USERNAME/weather-app.git

  #           cd weather-app

  #           git pull

  #           docker stop weather-container || true
  #           docker rm weather-container || true

  #           docker build -t weather-app .

  #           docker run -d -p 80:80 --name weather-container weather-app
